language: python
python:
  - "3.6.5"
  
# command to install dependencies
install:
 - apt-get install unixodbc-dev
 - apt-get install python-pip
 - travis_wait pip install -r requirements.txt
 - travis_wait pip install -r opt-requirements.txt
 - travis_wait pip install coverage
 - travis_wait pip install coveralls

jobs:
    include:
    - stage: "Tests"
      name: "testcheck1"
      script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_check1.py
    - script:  travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_check.py
      name: "testcheck"
    - script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_main1.py
      name: "test main function1"
    - script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_main2.py
      name: "test main function2"
    - script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_main3.py
      name: "test main function3"
    - script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_main4.py
      name: "test main function4"
    - script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_early_stops1.py
      name: "test stops1"
    - script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_early_stops2.py
      name: "test stops2"
    - script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_early_stops3.py
      name: "test stops3"

# command to run tests
#script:
##travis_wait 30 nosetests  --with-coverage --cover-package=flame_db
# - travis_wait 100 nosetests  --with-coverage --cover-package=flame_db
after_success:
    coveralls


