language: python
python:
  - "3.6.5"
  
# command to install dependencies
install:
 - travis_wait pip install -r requirements.txt
 - travis_wait pip install coverage
 - travis_wait pip install coveralls

jobs:
    include:
    - stage: "Tests"
      name: "testcheck1"
      script: nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_check1.py
    - script:  nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_check.py
      name: "testcheck2"
    - script: nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_main.py
      name: "test main function"
    - script: nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_early_stops1.py
      name: "test stops1"
#    - script: nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_early_stops2.py
#      name: "test stops2"

# command to run tests
#script:
##travis_wait 30 nosetests  --with-coverage --cover-package=flame_db
# - travis_wait 100 nosetests  --with-coverage --cover-package=flame_db
after_success:
    coveralls


