language: python
python:
  - "3.6.5"

services:
  - postgresql
#  - mysql


# command to install dependencies
install:
 - travis_wait pip install -r requirements.txt
 - travis_wait pip install coverage
 - travis_wait pip install coveralls
 

jobs:
    include:
    - name: "test main function1"
      before_script: psql -c 'create database tmp;' -U postgres
      script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_main1.py
    - name: "test main function2"
      before_script: psql -c 'create database tmp;' -U postgres
      script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_main2.py
    - name: "test main function4"
      before_script: psql -c 'create database tmp;' -U postgres
      script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_main4.py
    - name: "testcheck"
      before_script: psql -c 'create database tmp;' -U postgres
      script:  travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_check.py
    - name: "testcheck1"
      before_script: psql -c 'create database tmp;' -U postgres
      script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_check1.py
    - name: "test stops1"
      before_script: psql -c 'create database tmp;' -U postgres
      script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_early_stops1.py
    - name: "test stops2"
      before_script: psql -c 'create database tmp;' -U postgres
      script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_early_stops2.py
    - name: "test stops3"
      before_script: psql -c 'create database tmp;' -U postgres
      script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_early_stops3.py
#    - name: "test main function3 mysql"
#      before_script: mysql -e 'CREATE DATABASE IF NOT EXISTS tmp ;'
#      script: travis_wait 30 nosetests  --with-coverage --cover-package=flame_db tests1/flame_db_test_main3.py


after_success:
    coveralls


