language: python
python:
  - "3.6.5"
  
# command to install dependencies
install:
 - travis_wait pip install -r requirements.txt
 - travis_wait pip install coverage
 - travis_wait pip install coveralls

jobs:
    include:
    - stage: "Tests"
      name: "test1"
      script: - travis_wait 100 nosetests  --with-coverage tests1/flame_db_test1.py
    - script: - travis_wait 100 nosetests  --with-coverage tests1/flame_db_test.py
      name: "test2"
    - stage: "get coverage"
after_success:
    coveralls

# command to run tests
#script:
#travis_wait 30 nosetests  --with-coverage --cover-package=flame_db
# - travis_wait 100 nosetests  --with-coverage --cover-package=flame_db



